In [2]:
import numpy
import pandas
from pycm import *
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline

Using TensorFlow backend.


In [0]:

# fix random seed for reproducibility
seed = 7
numpy.random.seed(seed)

In [0]:
epochs=300
batch_size=2

In [0]:
# load dataset
dataframe = pandas.read_csv("feature_matrix_text_topics.csv")
dataset = dataframe.values
X = dataset[:,2:80].astype(float) #features
Y = dataset[:,1] #target      

In [6]:
dataset

array([['A-T', 'Modifer', 0.0, ..., 0.0, 0.0, 0.0],
       ['AAPC', 'Modifer', 0.0, ..., 0.0, 0.0, 0.0],
       ['AAS', 'Modifer', 0.0, ..., 0.0, 0.0, 0.0],
       ...,
       ['white matter lesions', 'DiseaseClass', 0.0, ..., 0.0, 0.0, 0.0],
       ['widened vestibular aqueduct', 'SpecificDisease', 0.0, ..., 0.0,
        0.0, 0.0],
       ['xanthoma', 'DiseaseClass', 0.0, ..., 0.0, 0.0, 0.0]],
      dtype=object)

In [7]:
Y

array(['Modifer', 'Modifer', 'Modifer', ..., 'DiseaseClass',
       'SpecificDisease', 'DiseaseClass'], dtype=object)

In [0]:
# encode class values as integers
encoder = LabelEncoder()
encoder.fit(Y)
encoded_Y = encoder.transform(Y)
# convert integers to dummy variables (i.e. one hot encoded)
dummy_y = np_utils.to_categorical(encoded_Y)

In [9]:
dummy_y

array([[0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       ...,
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.]], dtype=float32)

In [0]:
# define baseline model
def baseline_model():
	# create model
	model = Sequential()
	model.add(Dense(20, input_dim=39, activation='relu')) #dimension is number of features
	model.add(Dense(3, activation='sigmoid')) #no of classes
	# Compile model
	model.compile(loss='categorical_crossentropy', optimizer='adamax', metrics=['accuracy'])
	return model

In [0]:
# define baseline model
def second_model():
  # create model
  model = Sequential()
  #dimension is number of features
  model.add(Dense(20, input_dim=78, activation='relu'))
  model.add(Dense(20, activation='relu'))
  model.add(Dropout(0.5))
  model.add(Dense(20, activation='relu'))
  model.add(Dropout(0.5))
  model.add(Dense(4, activation='sigmoid')) #no of classes
  # Compile model
  model.compile(loss='categorical_crossentropy', optimizer='adamax', metrics=['accuracy'])
  return model

In [0]:
#estimator = KerasClassifier(build_fn=second_model, epochs=10, batch_size=5, verbose=0) #baseline

In [0]:
estimator = KerasClassifier(build_fn=second_model, epochs=epochs, batch_size=batch_size, verbose=0) 

In [0]:
#kfold = KFold(n_splits=10, shuffle=True, random_state=seed)

In [0]:
#results = cross_val_score(estimator, X, dummy_y, cv=kfold)
#print("Baseline: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100))

In [15]:
Y

array(['Modifer', 'Modifer', 'Modifer', ..., 'DiseaseClass',
       'SpecificDisease', 'DiseaseClass'], dtype=object)

In [20]:
estimator.fit(X,dummy_y)

In [21]:
y_predict = estimator.predict(X, batch_size=2, verbose=1, steps=None) 

2136/2136 [==============================] - 0s 220us/step


In [22]:
y_predict

array([3, 3, 3, ..., 3, 3, 3])

In [0]:
y_actual = []
for i in Y:
    if i == 'DiseaseClass':
        y_actual.append(1)
    elif i == 'SpecificDisease':
        y_actual.append(3)
    elif i == 'Modifier':
        y_actual.append(2)
    else:
        y_actual.append(0)

In [0]:
y_predict = [y for y in y_predict]

In [23]:
print(len(encoded_Y), len(y_predict))

2136 2136


In [24]:
cm = ConfusionMatrix(actual_vector=encoded_Y, predict_vector=y_predict) # Create CM From Data
cm.classes

[0, 1, 2, 3]

In [25]:
cm.table
print(cm)

Predict          0       1       2       3       
Actual
0                38      12      0       62      

1                0       235     0       336     

2                5       0       13      204     

3                6       26      0       1199    





Overall Statistics : 

95% CI                                                           (0.6757,0.71475)
AUNP                                                             0.65255
AUNU                                                             0.63606
Bennett S                                                        0.59363
CBA                                                              0.36879
Chi-Squared                                                      1210.95429
Chi-Squared DF                                                   9
Conditional Entropy                                              0.49189
Cramer V                                                         0.43471
Cross Entropy                                    

In [0]:
y_predict

array([3, 3, 3, ..., 3, 3, 3])

In [0]:
from numpy import array
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.embeddings import Embedding
from keras.preprocessing.text import text_to_word_sequence

In [0]:
file = open("text.txt", "r")
lines = file.read()

In [28]:
from keras.preprocessing.text import text_to_word_sequence
# estimate the size of the vocabulary
words = set(text_to_word_sequence(lines))
vocab_size = len(words)
print(vocab_size)

8265


In [49]:
words

{'incubated',
 'venous',
 'brother',
 'possibility',
 'tsd',
 'triggered',
 'fabry',
 'degrees',
 'ma',
 'template',
 'reacted',
 'infected',
 'unexpected',
 'pain',
 'sixteen',
 'neuroepithelium',
 'shared',
 'approximate',
 'tcf',
 'conformational',
 'hnpcc',
 '21a',
 'aerobic',
 'seeking',
 'excessive',
 'puex',
 'glyoxalase',
 'furthermore',
 'characterize',
 'daf',
 'elaborated',
 'harmfully',
 'flow',
 'gac',
 'hidden',
 'preformed',
 'possess',
 'pseudogene',
 'immunosuppression',
 'injected',
 'easy',
 'accepted',
 '142',
 'soon',
 'kilodalton',
 '70k',
 'happened',
 'notable',
 'h371r',
 '682c',
 'reveal',
 'photon',
 'sulphate',
 'bacteria',
 '000',
 'establishes',
 'zf',
 'erythematosus',
 'assoc',
 'apoc2',
 'frequent',
 'allosteric',
 't',
 'vlcfa',
 'measuring',
 'belongs',
 'spouses',
 'fewer',
 'lies',
 'pressure',
 'rarer',
 'amplify',
 'hex',
 'ctg',
 'about',
 'dxs164',
 '9',
 'otc',
 'subtypes',
 'consensus',
 'united',
 'delta',
 'estrogens',
 'dose',
 'galactosemi

In [0]:
from keras.preprocessing.text import Tokenizer

t = Tokenizer(filters='!"#$%&()*+,-./:;<=>?@[\]^_`{|}~ ', lower=True, split=' ', 
              char_level=False, oov_token=None)
tokens = t.fit_on_texts(words)

In [30]:

# summarize what was learned
print(t.word_counts)
print(t.document_count)
print(t.word_index)
print(t.word_docs)

OrderedDict([('incubated', 1), ('venous', 1), ('brother', 1), ('possibility', 1), ('tsd', 1), ('triggered', 1), ('fabry', 1), ('degrees', 1), ('ma', 1), ('template', 1), ('reacted', 1), ('infected', 1), ('unexpected', 1), ('pain', 1), ('sixteen', 1), ('neuroepithelium', 1), ('shared', 1), ('approximate', 1), ('tcf', 1), ('conformational', 1), ('hnpcc', 1), ('21a', 1), ('aerobic', 1), ('seeking', 1), ('excessive', 1), ('puex', 1), ('glyoxalase', 1), ('furthermore', 1), ('characterize', 1), ('daf', 1), ('elaborated', 1), ('harmfully', 1), ('flow', 1), ('gac', 1), ('hidden', 1), ('preformed', 1), ('possess', 1), ('pseudogene', 1), ('immunosuppression', 1), ('injected', 1), ('easy', 1), ('accepted', 1), ('142', 1), ('soon', 1), ('kilodalton', 1), ('70k', 1), ('happened', 1), ('notable', 1), ('h371r', 1), ('682c', 1), ('reveal', 1), ('photon', 1), ('sulphate', 1), ('bacteria', 1), ('000', 1), ('establishes', 1), ('zf', 1), ('erythematosus', 1), ('assoc', 1), ('apoc2', 1), ('frequent', 1), (

In [31]:
# integer encode documents
encoded_docs = t.texts_to_matrix(words, mode='count')
print(encoded_docs)

[[0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [0]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=78, stop_words='english')
input_nn = tfidf.fit_transform(words)

In [33]:
input_nn

<8265x78 sparse matrix of type '<class 'numpy.float64'>'
	with 78 stored elements in Compressed Sparse Row format>

In [34]:
features = tfidf.get_feature_names()
print(features)

['00', 'neuro', 'neurobehavioral', 'neuroblastoma', 'neurodegeneration', 'neurodegenerative', 'neurodevelopmental', 'neurodevelopmentally', 'neuroectodermal', 'neuroepithelium', 'neurofibrosarcoma', 'neurofibrosarcomas', 'neurogenetic', 'neurohypophyseal', 'neurologic', 'neurological', 'ninth', 'nitrilotriacetic', 'nitroblue', 'nitrophenol', 'nitrosourea', 'niueans', 'nkh', 'nlaiii', 'nm', 'nm23', 'nmjs', 'nocturnal', 'node', 'non', 'nonaffected', 'nonallelic', 'noncarrier', 'noncarriers', 'noncentrocytic', 'noncoding', 'nonconsanguineous', 'nonconserved', 'noncontiguous', 'nondeficient', 'nondeletion', 'nondenaturing', 'nondetectable', 'nondisjunction', 'nonedematous', 'nonexpanded', 'nonfunctional', 'nonhereditary', 'nonhomologous', 'noninvasive', 'nonketotic', 'nonmuscle', 'nonneonatal', 'nonneoplastic', 'nonneuronopathic', 'nonobligatory', 'nonpapillary', 'nonparametric', 'nonpolyposis', 'nonradioactive', 'nonrandom', 'nonsense', 'nonspecific', 'nonspherocytic', 'nonsyndromic', 'no

In [0]:
y = tfidf.inverse_transform(input_nn)
print(y)

[array([], dtype='<U17'), array([], dtype='<U17'), array([], dtype='<U17'), array([], dtype='<U17'), array([], dtype='<U17'), array([], dtype='<U17'), array([], dtype='<U17'), array([], dtype='<U17'), array([], dtype='<U17'), array([], dtype='<U17'), array([], dtype='<U17'), array([], dtype='<U17'), array([], dtype='<U17'), array([], dtype='<U17'), array([], dtype='<U17'), array([], dtype='<U17'), array([], dtype='<U17'), array(['nondeficient'], dtype='<U17'), array([], dtype='<U17'), array([], dtype='<U17'), array([], dtype='<U17'), array([], dtype='<U17'), array([], dtype='<U17'), array([], dtype='<U17'), array([], dtype='<U17'), array([], dtype='<U17'), array([], dtype='<U17'), array([], dtype='<U17'), array([], dtype='<U17'), array([], dtype='<U17'), array([], dtype='<U17'), array([], dtype='<U17'), array([], dtype='<U17'), array([], dtype='<U17'), array([], dtype='<U17'), array([], dtype='<U17'), array([], dtype='<U17'), array([], dtype='<U17'), array([], dtype='<U17'), array([], 

In [0]:
from keras.preprocessing.text import one_hot
# integer encode the documents
vocab_size = 2136
encoded_docs = [one_hot(d, vocab_size) for d in words]
print(encoded_docs)

[[368], [663], [2122], [1752], [412], [2059], [996], [1339], [491], [850], [104], [1615], [717], [2120], [649], [929], [1597], [454], [475], [1322], [1575], [149], [1240], [230], [1408], [1212], [1856], [1042], [1898], [505], [164], [1078], [138], [555], [464], [1947], [1620], [2064], [509], [846], [2116], [1053], [1609], [1469], [1266], [413], [821], [227], [1969], [1158], [1600], [1701], [680], [241], [850], [1996], [1840], [1141], [925], [899], [1299], [444], [619], [719], [847], [1642], [679], [1318], [1618], [836], [1785], [865], [1291], [1347], [1626], [933], [1882], [878], [1497], [1819], [614], [1071], [1357], [188], [311], [459], [72], [652], [2038], [534], [212], [1949], [1262], [1384], [157], [1268], [2121], [1349], [119], [1715], [177], [683], [822], [1218], [1773], [53], [613], [1346], [772], [1717], [1648], [1013], [239], [1528], [1594], [1893], [418], [104], [1461], [2098], [284], [829], [1920], [1906], [95], [1593], [871], [1071], [117], [490], [1530], [1502], [1134], [

In [0]:
# pad documents to a max length of 4 words
max_length = 35
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)


[[ 368    0    0 ...    0    0    0]
 [ 663    0    0 ...    0    0    0]
 [2122    0    0 ...    0    0    0]
 ...
 [ 485    0    0 ...    0    0    0]
 [1290    0    0 ...    0    0    0]
 [ 635    0    0 ...    0    0    0]]


In [0]:
estimator1 = KerasClassifier(build_fn=second_model, epochs=epochs, batch_size=batch_size, verbose=0)

In [48]:
y_input = encoder.transform(words)

ValueError: ignored

In [0]:
from keras.preprocessing.text import one_hot
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten

# fit the model
y_predict1 = estimator.predict(input_nn)

In [50]:
for i in y_predict1:
  print(i)

3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
1
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3


In [51]:
len(y_predict1)

8265

In [43]:
cm1 = ConfusionMatrix(actual_vector=encoded_Y, predict_vector=y_predict1) # Create CM From Data
cm1.classes

pycmVectorError: ignored

In [0]:
cm1.table
print(cm1)

Predict          0       1       2       3       
Actual
0                25      9       0       78      

1                0       193     0       378     

2                5       0       9       208     

3                0       25      0       1206    





Overall Statistics : 

95% CI                                                           (0.65095,0.69081)
AUNP                                                             0.62105
AUNU                                                             0.60294
Bennett S                                                        0.56117
CBA                                                              0.31167
Chi-Squared                                                      901.40954
Chi-Squared DF                                                   9
Conditional Entropy                                              0.43038
Cramer V                                                         0.37506
Cross Entropy                                    